---
- include_tasks: pacman.yml
- include_tasks: system.yml
- include_tasks: yay.yml
- include_tasks: desktop.yml
- include_tasks: wayland.yml
- include_tasks: bluetooth.yml
- include_tasks: cron.yml
- include_tasks: hostname.yml